# Create PersistentVolume
# change the ip of NFS server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code
  labels:
    app: nginx
    app: php
    tier: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs01
    # Exported path of your NFS server
    path: "/html"
